language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.4
  - DJANGO_VERSION=1.9.0
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r requirements-dev.txt
# command to run tests
script: make coverage
after_success: coveralls