language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.12 DJANGO_NOSE_VERSION=1.4.1
  - DJANGO_VERSION=1.6.11 DJANGO_NOSE_VERSION=1.4.1
  - DJANGO_VERSION=1.7.10 DJANGO_NOSE_VERSION=1.4.1
  - DJANGO_VERSION=1.8.16 DJANGO_NOSE_VERSION=1.4.1
  - DJANGO_VERSION=1.9.11 DJANGO_NOSE_VERSION=1.4.3
  - DJANGO_VERSION=1.10.3 DJANGO_NOSE_VERSION=1.4.4
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r requirements-dev.txt
  - pip install -q django-nose==$DJANGO_NOSE_VERSION
# command to run tests
script: make coverage
after_success: coveralls
